/**
 * Obsidian Plugin
 *
 * Integrates with an Obsidian vault to generate and manage notes.
 * All generated notes are written to OBSIDIAN_VAULT_PATH/AI/
 *
 * Commands:
 * - .obsidian test — generate a test note in vault/AI/
 */

import { writeFileSync, existsSync, mkdirSync } from "fs";
import { join } from "path";

const VAULT_PATH = process.env.OBSIDIAN_VAULT_PATH;
const AI_DIR = VAULT_PATH ? join(VAULT_PATH, "AI") : null;

function ensureAiDir() {
  if (!AI_DIR) throw new Error("OBSIDIAN_VAULT_PATH not set in .env");
  if (!existsSync(AI_DIR)) mkdirSync(AI_DIR, { recursive: true });
}

function todayStr() {
  return new Date().toISOString().slice(0, 10);
}

function writeNote(filename, content) {
  ensureAiDir();
  const filepath = join(AI_DIR, filename);
  writeFileSync(filepath, content, "utf-8");
  return filepath;
}

export default {
  name: "obsidian",

  help: {
    "obsidian test": "Generate a test note in your Obsidian vault",
  },

  commands: {
    obsidian: async (msg, { reply, claude }) => {
      if (!VAULT_PATH) {
        await reply("OBSIDIAN_VAULT_PATH is not set in .env");
        return;
      }

      const args = msg.text.trim().split(/\s+/).slice(1);
      const sub = args[0]?.toLowerCase();

      if (!sub || sub === "test") {
        const date = todayStr();
        const prompt = `Write a short motivational note for today, ${date}. 2-3 sentences. Plain text, no headers.`;
        const result = await claude(prompt);
        const content = result.result || result.content || "Hello from oyster-bot!";

        const filename = `test-${date}.md`;
        const md = `# Test Note — ${date}\n\n${content}\n\n---\n*Generated by oyster-bot*\n`;
        const filepath = writeNote(filename, md);

        await reply(`Note written to:\n\`${filepath}\``);
        return;
      }

      await reply(`Unknown subcommand: ${sub}\nAvailable: test`);
    },
  },
};
