/**
 * Obsidian Plugin
 *
 * Integrates with an Obsidian vault. Generates daily note templates in
 * configured folders at 6am PT, skipping files that already exist.
 *
 * Commands:
 * - .obsidian today  — create today's daily notes in Journal and Habits
 * - .obsidian test   — generate a test note in vault/AI/
 */

import { writeFileSync, existsSync, mkdirSync } from "fs";
import { join } from "path";

const VAULT_PATH = process.env.OBSIDIAN_VAULT_PATH;

function ensureDir(dir) {
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
}

function todayStr() {
  const d = new Date();
  const yyyy = d.getFullYear();
  const mm = String(d.getMonth() + 1).padStart(2, "0");
  const dd = String(d.getDate()).padStart(2, "0");
  return `${yyyy}-${mm}-${dd}`;
}

function journalTemplate(date) {
  return `# Journal — ${date}

## Morning
- How are you feeling today?

## Today's focus


## Gratitude
1.
2.
3.

## Notes


---
*Created by oyster-bot*
`;
}

function habitsTemplate(date) {
  return `# Habits — ${date}

## Daily habits
- [ ]
- [ ]
- [ ]

## Notes


---
*Created by oyster-bot*
`;
}

function createDailyNotes() {
  if (!VAULT_PATH) throw new Error("OBSIDIAN_VAULT_PATH not set in .env");

  const date = todayStr();
  const created = [];
  const skipped = [];

  const folders = [
    { name: "Journal", template: journalTemplate },
    { name: "Habits",  template: habitsTemplate  },
  ];

  for (const { name, template } of folders) {
    const dir = join(VAULT_PATH, name);
    ensureDir(dir);
    const filepath = join(dir, `${date}.md`);
    if (existsSync(filepath)) {
      skipped.push(`${name}/${date}.md`);
    } else {
      writeFileSync(filepath, template(date), "utf-8");
      created.push(`${name}/${date}.md`);
    }
  }

  return { created, skipped };
}

export default {
  name: "obsidian",

  help: {
    "obsidian today": "Create today's daily notes in Journal and Habits folders",
    "obsidian test":  "Generate a test note in vault/AI/",
  },

  commands: {
    obsidian: async (msg, { reply }) => {
      if (!VAULT_PATH) {
        await reply("OBSIDIAN_VAULT_PATH is not set in .env");
        return;
      }

      const sub = msg.text.trim().split(/\s+/)[1]?.toLowerCase();

      if (!sub || sub === "today") {
        const { created, skipped } = createDailyNotes();
        const lines = [];
        if (created.length) lines.push(`Created:\n${created.map((f) => `  • ${f}`).join("\n")}`);
        if (skipped.length) lines.push(`Already exists (skipped):\n${skipped.map((f) => `  • ${f}`).join("\n")}`);
        await reply(lines.join("\n\n") || "Nothing to do.");
        return;
      }

      if (sub === "test") {
        const dir = join(VAULT_PATH, "AI");
        ensureDir(dir);
        const date = todayStr();
        const filepath = join(dir, `test-${date}.md`);
        writeFileSync(filepath, `# Test — ${date}\n\nHello from oyster-bot!\n\n---\n*Generated by oyster-bot*\n`, "utf-8");
        await reply(`Test note written to:\n\`${filepath}\``);
        return;
      }

      await reply(`Unknown subcommand: ${sub}\nAvailable: today, test`);
    },
  },

  schedules: [
    {
      cron: process.env.OBSIDIAN_DAILY_CRON || "0 6 * * *",
      timezone: "America/Los_Angeles",
      label: "obsidian-daily-notes",

      handler: async ({ channels, config }) => {
        const { created, skipped } = createDailyNotes();

        if (created.length === 0) {
          console.log("[obsidian] Daily notes already exist, skipping");
          return;
        }

        console.log(`[obsidian] Created daily notes: ${created.join(", ")}`);

        const targetChatId = config.plugins?.targetChatId;
        const targetChannel = config.plugins?.targetChannel || "telegram";
        if (!targetChatId) return;
        const channel = channels.get(targetChannel);
        if (!channel) return;

        await channel.send(String(targetChatId), `📓 Daily notes created:\n${created.map((f) => `• ${f}`).join("\n")}`);
      },
    },
  ],
};
